import ExcelJS from "exceljs";
import type { RentRollReportModel } from "./rent-roll-types";
import type { ProfessionalRentRollPack } from "./professional-types";

const EUR_FMT = '"€"#,##0.00';

function excelColumnLetter(zeroBasedIndex: number): string {
  let n = zeroBasedIndex + 1;
  let s = "";
  while (n > 0) {
    const m = (n - 1) % 26;
    s = String.fromCharCode(65 + m) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

function styleHeaderRow(row: ExcelJS.Row) {
  row.font = { bold: true, color: { argb: "FFFFFFFF" } };
  row.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF1e3a5f" },
  };
  row.alignment = { vertical: "middle", wrapText: true };
}

export async function buildProfessionalRentRollExcel(
  report: RentRollReportModel,
  pack: ProfessionalRentRollPack,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = pack.meta.brandName;
  wb.created = new Date();

  const readme = wb.addWorksheet("00_Readme", { properties: { tabColor: { argb: "FF64748b" } } });
  readme.getColumn(1).width = 44;
  readme.getColumn(2).width = 72;
  const metaRows: [string, string][] = [
    ["Report", pack.meta.reportTitle],
    ["Brand", pack.meta.brandName],
    ["Period", `${pack.meta.periodStart} → ${pack.meta.periodEnd}`],
    ["Generated (UTC)", pack.meta.generatedAtIso],
    ["Generated by", pack.meta.generatedByEmail ?? pack.meta.generatedByUserId],
    ["Properties", pack.meta.propertyLines.map((p) => `${p.name} — ${p.addressLine}`).join("; ")],
    ["Note", "Amounts modeled ex-VAT unless column states gross. Verify VAT with your adviser."],
  ];
  metaRows.forEach(([a, b], i) => {
    readme.getRow(i + 1).values = [a, b];
  });
  readme.getRow(1).font = { bold: true };

  const exec = wb.addWorksheet("01_Executive", { properties: { tabColor: { argb: "FF0f766e" } } });
  exec.columns = [
    { header: "KPI", key: "k", width: 36 },
    { header: "Value (ex-VAT where noted)", key: "v", width: 28 },
  ];
  styleHeaderRow(exec.getRow(1));
  const ex = pack.executive;
  const execData = [
    ["Total revenue (ex-VAT)", ex.totalRevenueNet],
    ["VAT on revenue (indicative)", ex.vatOnRevenue],
    ["Total revenue (incl. VAT, indicative)", ex.totalRevenueGross],
    ["Average monthly revenue (ex-VAT)", ex.avgMonthlyRevenueNet],
    ["Indicative annual run-rate (ex-VAT, 3-mo avg ×12)", ex.indicativeAnnualRevenueNet ?? ""],
    ["Occupancy % (snapshot)", ex.occupancyWeightedPct ?? ""],
    ["Occupancy note", ex.occupancyNote],
  ];
  execData.forEach((row, i) => {
    const r = exec.getRow(i + 2);
    r.getCell(1).value = row[0];
    r.getCell(2).value = row[1];
    if (typeof row[1] === "number") r.getCell(2).numFmt = EUR_FMT;
  });

  const monthly = wb.addWorksheet("02_Monthly_revenue_VAT", { properties: { tabColor: { argb: "FF2563eb" } } });
  const headers = [
    "Month",
    "Basis",
    "Office net",
    "Office VAT",
    "Office gross",
    "Meeting net",
    "Meeting VAT",
    "Hot desk net",
    "Hot desk VAT",
    "Venue net",
    "Venue VAT",
    "Add-ons net",
    "Add-ons VAT",
    "Total net",
    "Total VAT",
    "Total gross",
  ];
  monthly.addRow(headers);
  styleHeaderRow(monthly.getRow(1));
  pack.monthlyRevenueVat.forEach((m, idx) => {
    const r = monthly.getRow(idx + 2);
    r.values = [
      m.monthKey,
      m.basis,
      m.office.net,
      m.office.vat,
      m.office.gross,
      m.meeting.net,
      m.meeting.vat,
      m.hotDesk.net,
      m.hotDesk.vat,
      m.venue.net,
      m.venue.vat,
      m.additionalServices.net,
      m.additionalServices.vat,
      m.total.net,
      m.total.vat,
      m.total.gross,
    ];
    for (let c = 3; c <= 16; c++) r.getCell(c).numFmt = EUR_FMT;
  });
  const firstData = 2;
  const lastData = pack.monthlyRevenueVat.length + 1;
  if (lastData >= firstData) {
    const sumRow = monthly.getRow(lastData + 2);
    sumRow.getCell(1).value = "Totals";
    sumRow.font = { bold: true };
    for (let col = 3; col <= 16; col++) {
      const letter = excelColumnLetter(col - 1);
      sumRow.getCell(col).value = { formula: `SUM(${letter}${firstData + 1}:${letter}${lastData + 1})` };
      sumRow.getCell(col).numFmt = EUR_FMT;
    }
  }

  const vat = wb.addWorksheet("03_VAT_summary", { properties: { tabColor: { argb: "FF7c3aed" } } });
  vat.addRow(["Section", "Category", "Rate %", "Net (ex-VAT)", "VAT", "Gross (incl. VAT)"]);
  styleHeaderRow(vat.getRow(1));
  pack.vatSummaryLines.forEach((l, i) => {
    const r = vat.getRow(i + 2);
    r.values = [l.section, l.category, l.ratePct, l.net, l.vat, l.gross];
    r.getCell(3).numFmt = "0.#\\%";
    for (let c = 4; c <= 6; c++) r.getCell(c).numFmt = EUR_FMT;
  });
  const vatNetRow = vat.getRow(pack.vatSummaryLines.length + 3);
  vatNetRow.values = [
    "Indicative net VAT position (output-only, revenue)",
    "",
    "",
    "",
    pack.netVatPositionIndicative,
    "",
  ];
  vatNetRow.getCell(5).numFmt = EUR_FMT;
  vatNetRow.font = { italic: true };

  const sources = wb.addWorksheet("04_Data_sources", { properties: { tabColor: { argb: "FFca8a04" } } });
  sources.addRow(["ID", "Label", "Detail", "Actual vs forecast", "Last update"]);
  styleHeaderRow(sources.getRow(1));
  pack.dataSources.forEach((d, i) => {
    sources.getRow(i + 2).values = [d.id, d.label, d.detail, d.basisActualVsForecast, d.lastRelevantUpdate];
  });
  sources.getColumn(3).width = 50;
  sources.getColumn(4).width = 40;

  const dq = wb.addWorksheet("05_Data_quality", { properties: { tabColor: { argb: "FFdc2626" } } });
  dq.addRow(["Note"]);
  styleHeaderRow(dq.getRow(1));
  pack.meta.dataQualityNotes.forEach((n, i) => {
    dq.getRow(i + 2).getCell(1).value = n;
  });
  const asm = wb.addWorksheet("06_Assumptions", { properties: { tabColor: { argb: "FF475569" } } });
  asm.addRow(["Assumption"]);
  styleHeaderRow(asm.getRow(1));
  pack.meta.assumptions.forEach((n, i) => {
    asm.getRow(i + 2).getCell(1).value = n;
  });

  if (report.sections.officeRents && report.officeRentRoll.length) {
    const off = wb.addWorksheet("07_Office_rent_roll");
    off.addRow([
      "Month",
      "Property",
      "Room",
      "Lessee",
      "Rent (ex-VAT model)",
      "Invoiced total",
      "Source note",
    ]);
    styleHeaderRow(off.getRow(1));
    report.officeRentRoll.forEach((o, i) => {
      off.getRow(i + 2).values = [
        o.monthKey,
        o.propertyName,
        o.roomNumber,
        o.lessee,
        o.contractMonthlyRent,
        o.invoicedTotal,
        "Contract accrual; invoice when present",
      ];
      off.getCell("E" + (i + 2)).numFmt = EUR_FMT;
      off.getCell("F" + (i + 2)).numFmt = EUR_FMT;
    });
  }

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
