import ExcelJS from "exceljs";
import type { NetIncomeReportModel } from "./net-income-types";
import type { ProfessionalNetIncomePack } from "./professional-types";

const EUR_FMT = '"€"#,##0.00';

function styleHeaderRow(row: ExcelJS.Row) {
  row.font = { bold: true, color: { argb: "FFFFFFFF" } };
  row.fill = {
    type: "pattern",
    pattern: "solid",
    fgColor: { argb: "FF1e3a5f" },
  };
}

export async function buildProfessionalNetIncomeExcel(
  report: NetIncomeReportModel,
  pack: ProfessionalNetIncomePack,
): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = pack.meta.brandName;

  const readme = wb.addWorksheet("00_Readme");
  readme.getColumn(1).width = 40;
  readme.getColumn(2).width = 70;
  const lines: [string, string][] = [
    ["Report", pack.meta.reportTitle],
    ["Brand", pack.meta.brandName],
    ["Period", `${pack.meta.periodStart} → ${pack.meta.periodEnd}`],
    ["Generated", pack.meta.generatedAtIso],
    ["Generated by", pack.meta.generatedByEmail ?? pack.meta.generatedByUserId],
  ];
  lines.forEach(([a, b], i) => {
    readme.getRow(i + 1).values = [a, b];
  });

  const exec = wb.addWorksheet("01_Executive");
  exec.addRow(["KPI", "Value"]);
  styleHeaderRow(exec.getRow(1));
  const e = pack.executive;
  const rows: [string, string | number][] = [
    ["Revenue ex-VAT", e.totalRevenueNet],
    ["VAT on revenue", e.vatOnRevenue],
    ["Revenue incl. VAT", e.totalRevenueGross],
    ["Costs ex-VAT", e.totalCostsNet ?? ""],
    ["VAT on costs (model)", e.vatOnCosts ?? ""],
    ["Costs incl. VAT", e.totalCostsGross ?? ""],
    ["Net operating result ex-VAT", e.netOperatingResult ?? ""],
    ["Net margin %", e.netMarginPct ?? ""],
    ["Indicative annual revenue (run-rate)", e.indicativeAnnualRevenueNet ?? ""],
    ["Indicative annual net (run-rate)", e.indicativeAnnualNetResult ?? ""],
    ["Occupancy % snapshot", e.occupancyWeightedPct ?? ""],
  ];
  rows.forEach(([k, v], i) => {
    const r = exec.getRow(i + 2);
    r.getCell(1).value = k;
    r.getCell(2).value = v;
    if (typeof v === "number") r.getCell(2).numFmt = k.includes("%") ? "0.0" : EUR_FMT;
  });

  const monthly = wb.addWorksheet("02_Monthly_P_L");
  monthly.addRow([
    "Month",
    "Basis",
    "Rev net",
    "Rev VAT",
    "Rev gross",
    "Cost net",
    "Cost VAT",
    "Cost gross",
    "Net ex-VAT",
  ]);
  styleHeaderRow(monthly.getRow(1));
  pack.monthlyRows.forEach((m, i) => {
    const r = monthly.getRow(i + 2);
    r.values = [
      m.monthKey,
      m.basis,
      m.revenue.net,
      m.revenue.vat,
      m.revenue.gross,
      m.costs.net,
      m.costs.vat,
      m.costs.gross,
      m.netOperatingExVat,
    ];
    for (let c = 3; c <= 9; c++) r.getCell(c).numFmt = EUR_FMT;
  });

  const chart = wb.addWorksheet("03_Revenue_trend");
  chart.addRow(["Month", "Revenue net (ex-VAT)", "Net result ex-VAT"]);
  styleHeaderRow(chart.getRow(1));
  report.portfolioByMonth.forEach((pm, i) => {
    const r = chart.getRow(i + 2);
    r.values = [pm.monthKey, pm.revenue.total, pm.netIncome];
    r.getCell(2).numFmt = EUR_FMT;
    r.getCell(3).numFmt = EUR_FMT;
  });
  const lr = 1 + report.portfolioByMonth.length;
  chart.getRow(lr + 2).values = ["Chart hint", "Select columns A:C and insert an Excel chart for the board pack.", ""];

  const vat = wb.addWorksheet("04_VAT_summary");
  vat.addRow(["Section", "Category", "Rate %", "Net", "VAT", "Gross"]);
  styleHeaderRow(vat.getRow(1));
  pack.vatSummaryLines.forEach((l, i) => {
    const r = vat.getRow(i + 2);
    r.values = [l.section, l.category, l.ratePct, l.net, l.vat, l.gross];
    r.getCell(3).numFmt = "0.#\\%";
    for (let c = 4; c <= 6; c++) r.getCell(c).numFmt = EUR_FMT;
  });
  const vatIndRow = vat.getRow(pack.vatSummaryLines.length + 3);
  vatIndRow.values = ["Indicative net VAT (output − input model)", "", "", "", pack.netVatPositionIndicative, ""];
  vatIndRow.getCell(5).numFmt = EUR_FMT;

  const src = wb.addWorksheet("05_Data_sources");
  src.addRow(["ID", "Label", "Detail", "Actual vs forecast"]);
  styleHeaderRow(src.getRow(1));
  pack.dataSources.forEach((d, i) => {
    src.getRow(i + 2).values = [d.id, d.label, d.detail, d.basisActualVsForecast];
  });

  const dq = wb.addWorksheet("06_Data_quality");
  dq.addRow(["Note"]);
  styleHeaderRow(dq.getRow(1));
  pack.meta.dataQualityNotes.forEach((n, i) => {
    dq.getRow(i + 2).getCell(1).value = n;
  });

  const buf = await wb.xlsx.writeBuffer();
  return Buffer.from(buf);
}
